SELECT queryA.presupuestoId, queryA.userFirstName, jsonb_build_object('clientId', queryA.clientId, 'clientName', queryA.clientName, 'clientCuit', queryA.clientCuit) AS presupuestoClient, queryA.formaDePagoName, queryA.presupuestoAddress, json_agg(json_build_object('productId', queryA.presupuestoProductId, 'productQuantity', queryA.presupuestoProductQuantity, 'productDiscount', queryA.presupuestoProductDiscount, 'productSelectedAccessories', queryA.productSelectedAccessories)) AS presupuestoProducts FROM 
(SELECT Presupuestos.presupuestoId, Users.userFirstName, Clients.clientId, Clients.clientName, Clients.clientCuit, FormasDePago.formaDePagoName, Presupuestos.presupuestoAddress, Mesquita.PresupuestoProducts.presupuestoProductId, Mesquita.PresupuestoProducts.presupuestoProductQuantity, Mesquita.PresupuestoProducts.presupuestoProductDiscount, json_agg(json_build_object('presupuestoProductAccessoryId', Mesquita.PresupuestoProductAccessories.presupuestoProductAccessoryId, 'presupuestoProductAccesoryName', Mesquita.Products.productName,  'presupuestoProductAccessoryQuantity', Mesquita.PresupuestoProductAccessories.presupuestoProductAccessoryQuantity, 'presupuestoProductAccessoryDiscount', Mesquita.PresupuestoProductAccessories.presupuestoProductAccessoryDiscount, 'presupuestoProductAccessoryPrice', Mesquita.Products.productPrice)) AS productSelectedAccessories FROM Mesquita.Presupuestos
RIGHT JOIN Mesquita.PresupuestoProducts ON Mesquita.PresupuestoProducts.presupuestoId = Mesquita.Presupuestos.presupuestoId
INNER JOIN Mesquita.Users ON Mesquita.Users.userId = Mesquita.Presupuestos.userId
INNER JOIN Mesquita.Clients ON Mesquita.Clients.clientId = Mesquita.Presupuestos.clientId
INNER JOIN Mesquita.FormasDePago ON Mesquita.FormasDePago.formaDePagoId = Mesquita.Presupuestos.formaDePagoId
RIGHT JOIN Mesquita.PresupuestoProductAccessories ON Mesquita.PresupuestoProductAccessories.presupuestoProductId = Mesquita.PresupuestoProducts.presupuestoProductId
INNER JOIN Mesquita.Products ON Mesquita.Products.productId = Mesquita.PresupuestoProductAccessories.productId
GROUP BY Presupuestos.presupuestoId, Users.userFirstName, Clients.clientId, Clients.clientName, Clients.clientCuit, FormasDePago.formaDePagoName, Presupuestos.presupuestoAddress, Mesquita.PresupuestoProducts.presupuestoProductId, Mesquita.PresupuestoProducts.presupuestoProductQuantity, Mesquita.PresupuestoProducts.presupuestoProductDiscount) AS queryA
GROUP BY queryA.presupuestoId, queryA.userFirstName, presupuestoClient, queryA.formaDePagoName, queryA.presupuestoAddress

